REFERENCE_NAMES = [
    {"ru": "Акт", "en": "Act"},
    {"ru": "Акт и протоколы квалификационных испытаний", "en": "Certificate and protocols of qualification tests"},
    {"ru": "Акт и протоколы приемочных испытаний", "en": "Acceptance Test Report and protocols"},
    {"ru": "Акт испытаний", "en": "Test Act"},
    {"ru": "Альбом схем", "en": "Set of diagrams"},
    {"ru": "Альбом схем и чертежей", "en": "Set of diagrams and drawings"},
    {"ru": "Альбом чертежей", "en": "Set of drawings"},
    {"ru": "Ведомость", "en": "List / Statement"},
    {"ru": "Ведомость документов для ремонта", "en": "List of documents for repair"},
    {"ru": "Ведомость ЗИП на ремонт", "en": "List of spare parts for repair"},
    {"ru": "Ведомость калибровочного комплекта", "en": "Calibration kit statement"},
    {"ru": "Ведомость монтажного комплекта", "en": "mounting kit"},
    {"ru": "Ведомость пусконаладочного комплекта", "en": "Statement of the commissioning kit"},
    {"ru": "Ведомость тестового комплекта", "en": "Statement of the test set"},
    {"ru": "Ведомость эксплуатационной документации", "en": "Statement of operational documentation"},
    {"ru": "Гарантийный талон (гарантийный документ)", "en": "Warranty Document"},
    {"ru": "Декларация", "en": "Declaration"},
    {"ru": "Декларация соответсвия СЕ", "en": "Declaration of conformity CE"},
    {"ru": "Декларация соответствия ЕС", "en": "Declaration of conformity EU"},
    {"ru": "Декларация ТР ТС", "en": "Declaration of the TR CU"},
    {"ru": "Документы для ремонта", "en": "repair documents"},
    {"ru": "Заводской  номер", "en": "serial number"},
    {"ru": "Заключение", "en": "Conclusion"},
    {"ru": "Заключение об инспекции", "en": "Inspection report"},
    {"ru": "Инструкция", "en": "Instruction"},
    {"ru": "Инструкция по консервации", "en": "Instruction on conservation / preservation routine"},
    {"ru": "Инструкция по консервации (расконсервации), транспортировке, хранению", "en": "Instruction / Protocol for conservation (deconservation), transportation, storage"},
    {"ru": "Инструкция по монтажу", "en": "Installation instructions"},
    {"ru": "Инструкция по монтажу и наладке", "en": "Installation and setup protocol"},
    {"ru": "Инструкция по настройке", "en": "Setup Instruction"},
    {"ru": "Инструкция по применению", "en": "Application instructions"},
    {"ru": "Инструкция по применению", "en": "Instructions for use"},
    {"ru": "Инструкция по сборке", "en": "Assembly / Setup instructions"},
    {"ru": "Инструкция по техническому обслуживанию", "en": "Maintenance protocol / Maintenance instruction"},
    {"ru": "Инструкция по хранению, проведению консервации и срокам переконсервации", "en": "Instructions for storage, conservation and terms of re-preservation"},
    {"ru": "Инструкция по эксплуатации", "en": "Operation manual / Operating instructions / User Manual"},
    {"ru": "Информационное письмо", "en": "Information letter"},
    {"ru": "Испытание", "en": "Test"},
    {"ru": "Каталог сборочных единиц и деталей", "en": "Catalog of assembly units and parts"},
    {"ru": "Комплект", "en": "Set"},
    {"ru": "Комплект Актов испытаний", "en": "Set of Test Acts"},
    {"ru": "Комплект дополнительного оборудования", "en": "additional equipment kit"},
    {"ru": "Комплект протоколов испытаний", "en": "Set of test protocols"},
    {"ru": "Комплект технологических документов на ремонт", "en": "Set of technological documents for repair"},
    {"ru": "Комплект чертежей", "en": "Set of drawings"},
    {"ru": "Комплектовочная ведомость", "en": "Packing list"},
    {"ru": "Краткое руководство пользователя", "en": "Quick user guide"},
    {"ru": "Лист", "en": "List"},
    {"ru": "Лист контроля качества", "en": "Production and quality control list"},
    {"ru": "Лицензия", "en": "Licence"},
    {"ru": "Лицензия изготовителя", "en": "Licence of manufacturer"},
    {"ru": "Лицензия изготовителя на изготовление оборудования ОИАЭ", "en": "Manufacturer's license for the manufacture of equipment OIAE"},
    {"ru": "Лицензия на конструирование", "en": "Licence for design"},
    {"ru": "Лицензия разработчика на конструирование оборудования ОИАЭ", "en": "Developer's license for the design of OIAE equipment"},
    {"ru": "Методика", "en": "Procedure / method"},
    {"ru": "Методика поверки", "en": "Verification /  Calibration procedure"},
    {"ru": "Монтажный комплект", "en": "Mounting kit"},
    {"ru": "неразрушающий контроль", "en": "non-destructive testing"},
    {"ru": "Обоснование безопасности", "en": "Safety justification"},
    {"ru": "Описание / Брошюра", "en": "Description / Brochure"},
    {"ru": "Отгрузочная таблица", "en": "Shipping table"},
    {"ru": "Отказное письмо по сертификации", "en": "Explanatory Letter on certification"},
    {"ru": "Отчет", "en": "Report"},
    {"ru": "Отчет о патентной чистоте", "en": "Patent Purity Report"},
    {"ru": "Отчет о патентных исследованиях", "en": "Patent Research Report"},
    {"ru": "Отчет о патентных решениях", "en": "Report on patent solutions"},
    {"ru": "Отчет о поверке", "en": "Calibration / Verification Report"},
    {"ru": "Паспорт", "en": "Passport / Datasheet"},
    {"ru": "Паспорт-Формуляр", "en": "Data sheet – Form"},
    {"ru": "Патентные исследования", "en": "Patent research"},
    {"ru": "Патентный формуляр", "en": "Patent pattern"},
    {"ru": "Перечень", "en": "List"},
    {"ru": "Письмо", "en": "Letter"},
    {"ru": "Письмо о согласовании ремонтной документации", "en": "Letter of approval of repair documentation"},
    {"ru": "Письмо о согласовании эксплуатационной документации (ЭД)", "en": "Letter on approval of the Operational documentation"},
    {"ru": "Письмо разъяснение", "en": "Explantory Letter"},
    {"ru": "Письмо про протоколы испытаний", "en": "Letter on Test Protocols"},
    {"ru": "План качества", "en": "Quality plan"},
    {"ru": "План управления старением оборудования", "en": "Equipment Aging Management Plan"},
    {"ru": "поверка", "en": "Verification / Calibration"},
    {"ru": "покупное изделие", "en": "purchased item / product"},
    {"ru": "Приемо-сдаточное испытание", "en": "Acceptance and Delivery Test"},
    {"ru": "Приемочное испытание", "en": "Acceptance Test / Factory acceptance test"},
    {"ru": "Приложение", "en": "Annex"},
    {"ru": "Программа", "en": "Program"},
    {"ru": "Программа и методика квалификационных испытаний", "en": "Program and methodology of qualification tests"},
    {"ru": "Программа и методика приемо-сдаточных испытаний", "en": "Program and methodology of acceptance tests"},
    {"ru": "Программа лекционно-практических занятий", "en": "Program of lectures and practical classes"},
    {"ru": "Программа пусконаладочных работ", "en": "Program of commissioning works"},
    {"ru": "Протокол", "en": "Protocol"},
    {"ru": "Протокол испытаний", "en": "Test protocol"},
    {"ru": "Протокол испытаний EMC", "en": "EMC Test Protocol / Report"},
    {"ru": "Протокол испытаний LVD", "en": "LVD Test  Protocol / Report"},
    {"ru": "Протокол приемо-сдаточных испытаний ПСИ", "en": "Protocol of acceptance tests of ADT"},
    {"ru": "ПСИ", "en": "ADT"},
    {"ru": "Рабочее место", "en": "workstation"},
    {"ru": "Разъяснительное письмо", "en": "Explanatory Letter"},
    {"ru": "Расчёт на прочность", "en": "Endurance calculation"},
    {"ru": "Расчет надежности", "en": "Reliability calculation"},
    {"ru": "Расчет пожаробезопасности", "en": "Fire safety Calculation"},
    {"ru": "Регистрационного удостоверение", "en": "Registration certificate"},
    {"ru": "Регламент технического обслуживания и ремонта", "en": "Maintenance and repair regulations"},
    {"ru": "Решение о применении ИКИ", "en": "Decision on the use of ICI"},
    {"ru": "Руководство", "en": "Manual"},
    {"ru": "Руководство", "en": "Manual / Guide"},
    {"ru": "Руководство оператора", "en": "Operator manual"},
    {"ru": "Руководство по монтажу", "en": "Installation guide"},
    {"ru": "Руководство по настройке и эксплуатации", "en": "Setup and operation manual"},
    {"ru": "Руководство по обслуживанию и ремонту", "en": "Maintenance and repair manual"},
    {"ru": "Руководство по ограниченной гарантии", "en": "Limited Warranty Guide"},
    {"ru": "Руководство по ремонту", "en": "Repair manual"},
    {"ru": "Руководство по техническому обслуживанию", "en": "Maintenance Guidelines"},
    {"ru": "Руководство по установке", "en": "Setup Guide"},
    {"ru": "Руководство по шефмонтажу", "en": "Supervision Guide"},
    {"ru": "Руководство по эксплуатации", "en": "User Manual"},
    {"ru": "Руководство по эксплуатации", "en": "User manual"},
    {"ru": "Руководство пользователя", "en": "User guide / Owner’s manual"},
    {"ru": "Свидетельство", "en": "Certificate / Attestation"},
    {"ru": "Свидетельство о поверке", "en": "Verification Report"},
    {"ru": "Свидетельство об утверждении типа", "en": "Type Approval"},
    {"ru": "Сертификат антисептической обработки пиломатериалов, применённых в упаковке оборудования", "en": "Certificate of antiseptic treatment of lumber, used in the packaging of equipment"},
    {"ru": "Сертификат калибровки", "en": "Calibration Certificate / Verification Certificate"},
    {"ru": "Сертификат облучения", "en": "Irradiation Certificate"},
    {"ru": "Сертификат ОИАЭ", "en": "OIAE Certificate"},
    {"ru": "Сертификат оценки", "en": "Assessment Certificate"},
    {"ru": "Сертификат производителей материалов и полуфабрикатов, содержащие данные по химическому составу и механическим свойствам", "en": "Certificate of manufacturers of materials and semi-finished products containing data on chemical composition and mechanical properties"},
    {"ru": "Сертификат происхождения (от производителя)", "en": "Manufacturer's Certificate of Origin"},
    {"ru": "Сертификат СЕ", "en": "Certificate of conformity CE"},
    {"ru": "Сертификат ТРТС", "en": "TR CU certificate"},
    {"ru": "Спецификация", "en": "Specification"},
    {"ru": "Спецификация сборочных единиц", "en": "Specification of assembly units"},
    {"ru": "Справочное Руководство", "en": "Reference Guide"},
    {"ru": "срок переконсервации", "en": "period of re-conservation"},
    {"ru": "Схема", "en": "Layout / Diagram"},
    {"ru": "Схема подключения", "en": "Connection diagram / sceme"},
    {"ru": "Схема раскрепления оборудования при транспортировке", "en": "Equipment transport fastening layout"},
    {"ru": "Схема раскрепления оборудования при его хранении на складе", "en": "Scheme of loosening the equipment during its storage in the warehouse"},
    {"ru": "Тендерная спецификация", "en": "Tender specification"},
    {"ru": "технические данные", "en": "Technical data"},
    {"ru": "Технические требования на ИЭК", "en": "Technical requirements for IEC"},
    {"ru": "Технические условия", "en": "Technical specifications"},
    {"ru": "Технические условия на ремонт", "en": "Technical conditions for repairs"},
    {"ru": "Технические характеристики", "en": "Technical specifications"},
    {"ru": "Технический паспорт", "en": "Technical passport"},
    {"ru": "Техническое задание", "en": "Terms of reference / Technical specification"},
    {"ru": "Техническое описание", "en": "Technical description"},
    {"ru": "Техническое описание и инструкция по эксплуатации", "en": "Technical description and operating instructions"},
    {"ru": "Техническое Руководство", "en": "Technical Manual"},
    {"ru": "Типовая модель", "en": "Typical model"},
    {"ru": "Транспортный эскиз", "en": "Transport sketch"},
    {"ru": "Уведомление", "en": "Notion"},
    {"ru": "Уведомление об инспекции", "en": "Inspection notice"},
    {"ru": "Удостоверение о приемочной инспекции", "en": "Acceptance inspection notion"},
    {"ru": "Упаковочные листы", "en": "Packing lists"},
    {"ru": "Упрощенная программа", "en": "Simplified program"},
    {"ru": "Упрощенная схема", "en": "Simplified scheme"},
    {"ru": "Формуляр", "en": "Record card"},
    {"ru": "Характеристики", "en": "Specification"},
    {"ru": "Экспертное заключение", "en": "Expert opinion"},
    {"ru": "эксплуатационные документы", "en": "operational documents"},
    {"ru": "Электрическая схема компонентов", "en": "Components electric diagram"},
    {"ru": "элемент / компонент", "en": "component"},
    {"ru": "Этикетка", "en": "Data sheet"},
    {"ru": "Cхема раскрепления оборудования при транспортировке на транспортном средстве", "en": "Scheme of loosening the equipment during transportation on a vehicle"},
]
